name: Test Environment Variable

on:
  workflow_dispatch:
  push:
    branches:
    - test

env:
  test: ${{ vars.TEST }}

jobs:
  getEnvVar:
    name: Get environment variable
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: get var
        run: echo "$test"
